### ISSUE TITLE
[Bug / Suggestion] Events not indicated on calendar

### ISSUE THREAD

**Issue by yilun-zhu** [PhaseBT14A2/addressbook-level4#113]
![image](https://user-images.githubusercontent.com/20789805/32363169-e345d504-c0a8-11e7-9345-7b11678fc5ea.png)
Hi, I assume that the events are supposed to show on the calendar. 
If its not supposed to be, I think it would be good to implement it

**Comment by kaiyu92** [comment]
Hi,

Thanks for noticing the bug.

Apparently, the problem lies at the date format.

The correct Datetime format should be:
**dd-MM-yyyy hhmm**

The sample data that is pre-loaded into the event book have the incorrect format as well. I've fixed that bug already. Sorry for not emphasising the format of the Datetime.

We actually have prepared a regex to enforce the correct Datetime format. However, it failed on Travis CI (Please refer to the link below).

https://github.com/nus-cs2103-AY1718S1/forum/issues/177

Regards,
Quek Kai Yu

**Comment by kaiyu92** [comment]
![image](https://user-images.githubusercontent.com/24559155/32374013-fd5e38cc-c0d6-11e7-8705-3cdeef1babbf.png)
